header:
  subtitle: "Know yourself better through AI agent analytics"

og:
  title: "Twi.am"
  description: "Know yourself better through AI agent analytics"
  image: "/favicon.png"
  url: "https://twi.am"
  type: "website"

products:
  - name: "Twitter MBTI Receipt"
    domain: "mbti.twi.am"
    description: "Generate a personalized MBTI receipt based on your Twitter activity"
    icon: "https://cdn.jsdelivr.net/gh/stvlynn/twi.am@main/favicon.ico"
    link: "https://mbti.twi.am"
    features:
      - "Personality analysis based on tweets"
      - "Beautiful receipt-style format"
      - "Instant results"

  - name: "Twitter Instant Portrait"
    domain: "portrait.twi.am"
    description: "Transform your Twitter profile into stunning AI-generated portraits"
    link: "https://portrait.twi.am"
    icon: "https://cdn.jsdelivr.net/gh/stvlynn/TwitterInstantPortrait@main/public/favicon.png"
    features:
      - "AI-powered portrait generation"
      - "Multiple artistic styles"
      - "High-resolution output"

  - name: "Twitter Lottery"
    domain: "lottery.twi.am"
    description: "A free tool to randomly select winners from Twitter/X post replies. Perfect for giveaways, contests, and social media campaigns."
    link: "https://lottery.twi.am"
    icon: "https://cdn.jsdelivr.net/gh/stvlynn/TwitterLottery@main/public/favicon.png"
    features:
      - "Randomly select winners from Twitter/X post replies"

footer:
  links: 
    - text: "Twitter Follow"
      url: "https://twitter.com/stv_lynn"
      type: "twitter"
      image: "https://img.shields.io/twitter/follow/stv_lynn"
      
    - text: "Buy Me A Coffee"
      url: "https://www.buymeacoffee.com/stvlynn"
      type: "coffee"
      image: "https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png"

    - text: "Dify"
      url: "https://dify.ai"
      type: "dify"
      image: "https://assets.dify.ai/images/dify_logo_dark_s.png"

    - text: "License"
      url: "https://github.com/stvlynn/twi.am-page/blob/main/LICENSE"
      type: "license"
      image: "https://img.shields.io/github/license/stvlynn/twi.am-page?logo=github"